### ISSUE TITLE
EzBlocProvider.of(context) doesn't have a get method

### ISSUE THREAD

**Issue by DyaryRaoof** [Ephenodrom/EZ-Flutter#16]

**Comment by Ephenodrom** [comment]
Hello @DyaryRaoof 
The documentation is not up to date and will be updated this week. The correct way is :

```dart
EzBlocProvider.of<EzGlobalBloc>(context).get(...);
```
It is important to add **\<EzGlobalBloc\>** after the **of**.

**Comment by Ephenodrom** [comment]
No response from the author of the issue.
