### ISSUE TITLE
EzTranslator.of(context) returns null

### ISSUE THREAD

**Issue by racknoris** [Ephenodrom/EZ-Flutter#18]
The translation file seems to be loading because I don't get an error in the console, but ``` EzTranslator.of(context) ``` returns null.
Am I missing something?

**Comment by racknoris** [comment]
Figured it out. Originally I used: 
```void main() async => await EzRunner.run(MyApp(), "Ez Flutter App", locales: [Locale('en')]);```

and my MyApp class was:

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        initialRoute: "/",
        routes: {
          '/': (context) => Login(),
          "/login": (context) => Login(),
          "/profile": (context) => Profile(),
        }
    )
  }
}
```

After going through the source code, I noticed that EzRunner.run() already returns a MaterialApp with a different context than the one I return in my build method, that's why using ```EzTranslator.of(context)``` inside one of my other widgets (Login/Profile), didn't work.
At the moment, the plugin doesn't accept the ```initialRoute``` or ```routes``` parameters, so I'll create a pull request for that.

**Comment by racknoris** [comment]
the PR: #19

**Comment by Ephenodrom** [comment]
@racknoris 
Hello and thanks for the issue. The PR was accepted and the update on pub.dev will arrive at the latest on Thursday. Will inform you when the update is available.

**Comment by racknoris** [comment]
Hi!
No problem, and thank you for the quick response

**Comment by Ephenodrom** [comment]
@racknoris 
Hello! The update is available via pub.dev with version 0.4.1.

Feel free to contribute to this repository in the future :).

**Comment by racknoris** [comment]
@Ephenodrom great news, will do
